# SonarQube analysis settings
#
# The project key is set by the scanner invocation (-Dsonar.projectKey=...)
# sonar.projectKey=pyrad

sonar.sources=pyrad
sonar.python.version=3.10, 3.11, 3.12, 3.13, 3.14

# Exclude the test directories from the analysis
sonar.exclusions=pyrad/tests/**,tests/**
